image: Visual Studio 2019

init:
- net start MSSQL$SQL2019

before_build:
- cmd: nuget restore
- cmd: .\Deploy\initDatabaseUser.cmd (local)
- cmd: .\Deploy\setConnectionString.py "Server=(local)\SQL2019;Initial Catalog=SugarCounterTest;User ID=SugarCounterDev;Password=123;"

configuration: Release

build:
  verbosity: minimal

test_script:
- cmd: dotnet test "Tests\Unit\Unit.csproj" --configuration Release --no-build
- cmd: dotnet test "Tests\Integration\Integration.csproj" --configuration Release --no-build
- cmd: dotnet test "Tests\Functional\Functional.csproj" --configuration Release --no-build
