USE [master]
GO
CREATE LOGIN [CaloriesStorageDev] WITH PASSWORD='123', DEFAULT_DATABASE=[master], CHECK_EXPIRATION=OFF, CHECK_POLICY=OFF
GO
ALTER SERVER ROLE [dbcreator] ADD MEMBER [CaloriesStorageDev]
GO
